#!/usr/bin/env sh
# generates an ssl certificate for us to use, simple wrapper
# taken from http://cherrypy.readthedocs.org/en/latest/deploy.html#ssl-support
openssl genrsa -out privkey.pem 2048
openssl req -new -x509 -days 365 -key privkey.pem -out cert.pem
